name: Readwise data export
on:
  schedule:
    # At 00:00 on every 2nd day-of-month.
    - cron: 0 0 */2 * *
  workflow_dispatch:
jobs:
  readwise-data-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            main.py
            readwise.csv
            pyproject.toml
            uv.lock
          sparse-checkout-cone-mode: false
      - uses: astral-sh/setup-uv@v6
      - run: |
            uv run ./main.py > readwise.csv
        env:
          READWISE_READER_API_TOKEN: ${{ secrets.readwise_reader_api_token }}
      - run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Updated Readwise export" || exit 0
          git push
